In [16]:
def getNextStates():
  
  return 0

In [2]:
import numpy as np

In [12]:
class Encoder:
  def __init__(self, k, n, v, polynomial):  # constructor
    print("this is constructor")
    self.polynomial_ = polynomial # member variable
    self.k_ = k
    print(self.k_)
    self.n_ = n
    self.v_ = v
    self.num_states = 2**self.v_
    self.num_inputs = 2**self.k_
    self.next_states = self.computeNextStates()
    print(self.next_states)
    
    self.outputs_ = self.computeOutputs()
    
    
  def encode(self, message):
    print("this is encode")
    return message + self.k_
  
  def compute_code_rate(self):
    self.code_rate_ = self.k_ / self.n_
    
  def computeNextStates(self):
    # boilerplate code
    return next_states
  
  def computeOutputs(self):
    
    return outputs 
  

In [3]:
print(0b101)
print(0x5)


5
5


In [14]:
polynomial_1 = 0b101
k_1 = 3
n_1 = 6
v_1 = 2

polynomial_2 = 0b110
k_2 = 4
n_2 = 9
v_2 = 3

encoder_1 = Encoder(k_1, n_1, v_1, polynomial_1) # object construction
encoder_1.computeNextStates()  # okay

encoder_2 = Encoder(k_2, n_2, v_2, polynomial_2)

message = 0b10101
encoder_1.encode(message)

def compute_code_rate_from_outside():
  code_rate = encoder_1.k_ / encoder_1.n_
  

print("after change", encoder_1.polynomial_)

this is constructor
this is constructor
before change 5
after change 7


In [21]:
def decimalToBinary(digit):
    if digit == 0:
        binary = np.array([0,0,0])
    elif digit == 1:
        binary = np.array([0,0,1])
    elif digit == 2:
        binary = np.array([0,1,0])
    elif digit == 3:
        binary = np.array([0,1,1])
    elif digit == 4:
        binary = np.array([1,0,0])
    elif digit == 5:
        binary = np.array([1,0,1])
    elif digit == 6:
        binary = np.array([1,1,0])
    elif digit == 7:
        binary =np.array([1,1,1])
    else:
        print("Invalid Octal Digit")
    return binary

In [22]:
print(decimalToBinary(3))
print(type(decimalToBinary(3)))

[0 1 1]
<class 'numpy.ndarray'>


In [25]:
def octalToBinary(Octal):
    # octal = 13
    # binary = 000 000
    numOfDigits=len(str(abs(Octal)))
    polynomial=np.zeros((3*numOfDigits),dtype=int)

    # 2-digit case
    if numOfDigits == 2:
        b1=Octal//10
        b0=Octal%10
        polynomial[:3]=decimalToBinary(b1)
        polynomial[3:]=decimalToBinary(b0)
    # 3-digit case
    elif numOfDigits == 3:
        b2=Octal//100
        b1=(Octal%100)//10
        b0=Octal%10
        polynomial[:3]=decimalToBinary(b2)
        polynomial[3:6]=decimalToBinary(b1)
        polynomial[6:]=decimalToBinary(b0)
    # 4-digit case
    elif numOfDigits == 4:
        b3=Octal//1000
        b2=(Octal%1000)//100
        b1=(Octal%100)//10
        b0=Octal%10
        polynomial[:3]=decimalToBinary(b3)
        polynomial[3:6]=decimalToBinary(b2)
        polynomial[6:9]=decimalToBinary(b1)
        polynomial[9:]=decimalToBinary(b0)
    # 5-digit case
    elif numOfDigits == 5:
        b4=Octal//10000
        b3=(Octal%10000)//1000
        b2=(Octal%1000)//100
        b1=(Octal%100)//10
        b0=Octal%10
        polynomial[:3]=decimalToBinary(b4)
        polynomial[3:6]=decimalToBinary(b3)
        polynomial[6:9]=decimalToBinary(b2)
        polynomial[9:12]=decimalToBinary(b1)
        polynomial[12:]=decimalToBinary(b0)
    return polynomial
        

    

In [26]:
print(octalToBinary(17))
print(octalToBinary(133))
print(octalToBinary(561))
print(octalToBinary(1131))
print(octalToBinary(56711))
print(octalToBinary(27251))
print(octalToBinary(75063))
print(octalToBinary(16765))
print(decimalToBinary(56711%10))

[0 0 1 1 1 1]
[0 0 1 0 1 1 0 1 1]
[1 0 1 1 1 0 0 0 1]
[0 0 1 0 0 1 0 1 1 0 0 1]
[1 0 1 1 1 0 1 1 1 0 0 1 0 0 1]
[0 1 0 1 1 1 0 1 0 1 0 1 0 0 1]
[1 1 1 1 0 1 0 0 0 1 1 0 0 1 1]
[0 0 1 1 1 0 1 1 1 1 1 0 1 0 1]
[0 0 1]


In [53]:
print(53//10) # quotient
print(53%10)  # remainder

print(4325//10000)
# 4325
print(4325//1000)        # 4
print((4325%1000)//100)  # 325//100=3
print((4325%100)//10)    # 25//10=2
print(4325%10)           # 5

# 133
print(133//100)
print((133%100)//10)
print(133%10)

# 13
print(13//10)
print(13%10)

# count number of digits in 4325
print(len(str(abs(4325))))  # 4

# Creating a 3x4 array filled with zeros
v=3
polynomial=np.array([13, 17])
print(polynomial[0])
print(polynomial[1])

matlab_matrix = np.array([[13, 17],
                          [133, 171]])
print(matlab_matrix[1][0])

shape = (1,6)
zero_array = np.zeros(shape, dtype=str)
print(zero_array)

b=np.array([[0,0,1]])
b2=np.array([[0,1,1]])
zero_array[0,:3]=b
zero_array[0,3:]=b2
print(zero_array)

print(bin(19)[2:]) # string: 10011
print(0b10011)
print(type(bin(19)[2:]))

string_to_list=list(bin(19)[2:])        # list: '1','0','0','1','1'
char_array=np.array(string_to_list)  # array: ['1','0','0','1','1'] char type
print(type(char_array))
int_array=[int(char) for char in char_array]
print(int_array)

print(bin(0)[2:])
print(bin(1))
print(bin(2))
print(bin(3))
print(bin(4))
print(bin(5))
print(bin(6))
print(type(bin(7)[2:])) #str type
print(np.zeros((1,8),dtype=int))
a=np.array([1,1],dtype=int)
print(int(''.join(map(str,a)),2))



5
3
0
4
3
2
5
1
3
3
1
3
4
13
17
133
[['' '' '' '' '' '']]
[['0' '0' '1' '0' '1' '1']]
10011
19
<class 'str'>
<class 'numpy.ndarray'>
[1, 0, 0, 1, 1]
0
0b1
0b10
0b11
0b100
0b101
0b110
<class 'str'>
[[0 0 0 0 0 0 0 0]]
3


In [34]:
a=np.array([1,2,3,4,5],dtype=int)
v=3
print(a[-1*v])
print(len(a))
print(1%2)
print(0%2)

3
5
1
0


In [49]:
def binary_addition(a,b):
    if (a+b)%2==1:
        return 1
    elif (a+b)%2==0:
        return 0
    else:
        return "Invalid Input"
    
c0=1
c0=binary_addition(c0,1)
c0=binary_addition(c0,1)
c0=binary_addition(c0,1)
print(c0)

0


In [74]:
v=8
numStates=2**v
numInputSymbols=2
p0_octal=561
p0_binary=octalToBinary(p0_octal)  # [0 0 1 0 1 1]
print(p0_binary)
p1_octal=753
p1_binary=octalToBinary(p1_octal)  # [0 0 1 1 1 1]
print(p1_binary)

output_matrix=np.zeros((numStates,numInputSymbols), dtype=int)
for i in range(1,numStates+1):
    # initialize state: 000 (1x3)
    current_state=np.zeros((v),dtype=int)
    state_in_binary=np.array([int(char) for char in bin(i-1)[2:]])
    start_index=len(current_state)-len(state_in_binary)
    current_state[start_index:]=state_in_binary.reshape(1,len(state_in_binary))  


    output_in_binary=np.zeros(2, dtype=int)
    # input: 0
    u0=0
    # output: [c0 c1]
    c0=u0 
    c1=u0
    for j in range(-v,0):
        c0=binary_addition(c0,current_state[j+v]*p0_binary[j])
        c1=binary_addition(c1,current_state[j+v]*p1_binary[j])
    output_in_binary[0]=c0
    output_in_binary[1]=c1
    output_matrix[i-1][0]=int(''.join(map(str,output_in_binary)),2)

    output_in_binary=np.zeros(2,dtype=int)

    # input: 1
    u0=1
    # output: [c0 c1]
    c0=u0 
    c1=u0
    for j in range(-v,0):
        c0=binary_addition(c0,current_state[j+v]*p0_binary[j])
        c1=binary_addition(c1,current_state[j+v]*p1_binary[j])
    output_in_binary[0]=c0
    output_in_binary[1]=c1
    output_matrix[i-1][1]=int(''.join(map(str,output_in_binary)),2)










[1 0 1 1 1 0 0 0 1]
[1 1 1 1 0 1 0 1 1]
[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 1 1]
[0 0 0 0 0 1 0 0]
[0 0 0 0 0 1 0 1]
[0 0 0 0 0 1 1 0]
[0 0 0 0 0 1 1 1]
[0 0 0 0 1 0 0 0]
[0 0 0 0 1 0 0 1]
[0 0 0 0 1 0 1 0]
[0 0 0 0 1 0 1 1]
[0 0 0 0 1 1 0 0]
[0 0 0 0 1 1 0 1]
[0 0 0 0 1 1 1 0]
[0 0 0 0 1 1 1 1]
[0 0 0 1 0 0 0 0]
[0 0 0 1 0 0 0 1]
[0 0 0 1 0 0 1 0]
[0 0 0 1 0 0 1 1]
[0 0 0 1 0 1 0 0]
[0 0 0 1 0 1 0 1]
[0 0 0 1 0 1 1 0]
[0 0 0 1 0 1 1 1]
[0 0 0 1 1 0 0 0]
[0 0 0 1 1 0 0 1]
[0 0 0 1 1 0 1 0]
[0 0 0 1 1 0 1 1]
[0 0 0 1 1 1 0 0]
[0 0 0 1 1 1 0 1]
[0 0 0 1 1 1 1 0]
[0 0 0 1 1 1 1 1]
[0 0 1 0 0 0 0 0]
[0 0 1 0 0 0 0 1]
[0 0 1 0 0 0 1 0]
[0 0 1 0 0 0 1 1]
[0 0 1 0 0 1 0 0]
[0 0 1 0 0 1 0 1]
[0 0 1 0 0 1 1 0]
[0 0 1 0 0 1 1 1]
[0 0 1 0 1 0 0 0]
[0 0 1 0 1 0 0 1]
[0 0 1 0 1 0 1 0]
[0 0 1 0 1 0 1 1]
[0 0 1 0 1 1 0 0]
[0 0 1 0 1 1 0 1]
[0 0 1 0 1 1 1 0]
[0 0 1 0 1 1 1 1]
[0 0 1 1 0 0 0 0]
[0 0 1 1 0 0 0 1]
[0 0 1 1 0 0 1 0]
[0 0 1 1 0 0 1 1]
[0 0 1 1 0 1 0 0]
[0 0 1

In [ ]:
state=np.zeros((1,3),dtype=int)
print(state)
i=3
print(bin(i-1)[2:])
print("Type of bin(i-1)[2:] is ", type(bin(i-1)[2:]))

binary_string=bin(i-1)[2:]

# convert string to array of int 
state_in_binary=np.array([int(char) for char in binary_string])
print(state_in_binary)
print(state_in_binary.shape)
print(type(state_in_binary))

start_index=len(state[0])-len(state_in_binary)
print(len(state[0]))
print(len(state_in_binary))
print(start_index)
print(state[start_index:])
state[0][start_index:]=state_in_binary.reshape(1,2)
print(state)

In [ ]:
numStates=8
for i in range(1,numStates+1):
    # initialize state: 000 (1x3)
    state=np.zeros((3),dtype=int)
    state_in_binary=np.array([int(char) for char in bin(i-1)[2:]])
    start_index=len(state)-len(state_in_binary) 
    state[start_index:]=state_in_binary.reshape(1,len(state_in_binary))
    print(state)

In [ ]:
array=np.array([1,2,3,4,5])
print(array)
print(len(array))

def Input0(arr):
    new_arr=np.zeros((len(arr)),dtype=int)
    print(new_arr)
    new_arr[1:]=arr[:-1]
    print(new_arr)
    return new_arr

print(array[:-1])
print(Input0(array))

In [ ]:
# next state matrix (8x2)
v_=3
numStates=2**v_
numInputSymbols=2
state_matrix=np.zeros((numStates,numInputSymbols),dtype=int)

print(int('000',2))
for i in range(1,numStates+1):

    # initialize state: 000 (1x3)
    current_state=np.zeros((v_),dtype=int)
    state_in_binary=np.array([int(char) for char in bin(i-1)[2:]])
    start_index=len(current_state)-len(state_in_binary)
    current_state[start_index:]=state_in_binary.reshape(1,len(state_in_binary))   

    # input = 0
    next_state_in_binary=''.join(map(str,Input0(current_state)))
    next_state=int(next_state_in_binary,2)
    print("The next state of ", current_state, " with input 0 is ", next_state)
    state_matrix[i-1][0]=next_state

    # input = 1
    next_state_in_binary=''.join(map(str,Input1(current_state)))
    next_state=int(next_state_in_binary,2)
    print("The next state of ", current_state, " with input 1 is ", next_state)
    state_matrix[i-1][1]=next_state

print(state_matrix)

In [ ]:
binary_array=np.array([1,0,0,1,1])
binary_string=''.join(map(str,binary_array))
print(binary_string)
print(int(binary_string,2))

In [77]:
print(7 >> 1) # 111 right shift by 1 equals 011

3
